#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["rich"]
# ///
"""Drone binary hasher — sha256-pins each cross-built `ubiq-drone` and emits its manifest.

Run it through `just`: `just drone-manifest` (snapshot), `just drone-manifest-verify` (drift
check). Neither fetches anything — a drone binary is built locally by `just drone-build`, never
downloaded, so this script's whole job is hashing bytes that are already on disk.

`snapshot` looks for `target/<triple>/release/ubiq-drone` (`.exe` on the two Windows triples) for
every triple in `TRIPLES` below. A triple with no built binary is skipped with a warning and left
out of the table — nobody has every cross toolchain installed, and an honest partial manifest beats
a failed run. `verify` re-reads the generated `.rs` with a regex, re-hashes each named binary on
disk, and reports drift as a table rather than keeping any state of its own — the generated file is
the only source of truth, the same shape `_tools/webassets.py`'s own `verify` uses.

This is deliberately not `webassets.py`'s shape everywhere: there is no CDN here, so there is no
fetching, no retry loop and no scratch cache — only `hashlib` and the filesystem.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

from rich.console import Console
from rich.table import Table

REPO = Path(__file__).resolve().parents[1]
MANIFEST = REPO / "crates/ubiq-proto/src/drone/manifest.rs"
DRONE_CARGO_TOML = REPO / "crates/ubiq-drone/Cargo.toml"

# The seven triples a deployed drone may be built for. Stated once, here, rather than derived from
# an installed toolchain list: `snapshot` must say what it could *not* build, and it can only say
# that against a fixed list.
TRIPLES = (
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
)

WINDOWS_TRIPLES = {"x86_64-pc-windows-msvc"}

console = Console()


@dataclass
class Built:
    triple: str
    path: Path
    sha256: str
    len: int


def die(message: str) -> None:
    console.print(f"[red]{message}[/red]")
    sys.exit(1)


def drone_version() -> str:
    """`ubiq-drone`'s own `CARGO_PKG_VERSION`, read from its manifest rather than duplicated here."""
    data = tomllib.loads(DRONE_CARGO_TOML.read_text())
    return data["package"]["version"]


def binary_path(triple: str) -> Path:
    name = "ubiq-drone.exe" if triple in WINDOWS_TRIPLES else "ubiq-drone"
    return REPO / "target" / triple / "release" / name


def hash_file(path: Path) -> tuple[str, int]:
    digest = hashlib.sha256()
    total = 0
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
            total += len(chunk)
    return digest.hexdigest(), total


def rust_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_manifest(version: str, built: list[Built]) -> str:
    lines = [
        "//! The cross-built `ubiq-drone` binaries a deployer can hand to a remote machine, with the",
        "//! SHA-256 [`crate::drone::verify`] checks a cached copy against.",
        "//!",
        "//! **This is hash-pinned, not signed.** There is no signing key and no release pipeline",
        "//! (`G108`); a mismatch here means the local build changed, not that a signature failed —",
        "//! saying \"signed\" would imply provenance this tree does not have.",
        "//!",
        "//! A triple with no locally built binary at snapshot time is simply absent from",
        "//! [`BINARIES`]: nobody has every cross toolchain installed, so a partial manifest is the",
        "//! honest state, not a failed run.",
        "//!",
        "//! @generated by `_tools/drone.py` — do not edit by hand.",
        "//! Regenerate with `just drone-manifest`; check for local drift with",
        "//! `just drone-manifest-verify`.",
        "",
        "/// One cross-built binary: which triple it runs on, where `snapshot` found it, and what it",
        "/// must hash to.",
        "pub struct Entry {",
        "    pub triple: &'static str,",
        "    pub path: &'static str,",
        "    pub sha256: &'static str,",
        "    pub len: u64,",
        "}",
        "",
        "/// `ubiq-drone`'s own `CARGO_PKG_VERSION` — the cache directory name a deployer keys its",
        "/// copy under, so two versions never collide on disk.",
        f'pub const VERSION: &str = "{version}";',
        "",
        f"/// The {len(built)} triple(s) built locally when this manifest was last regenerated, sorted",
        "/// by triple.",
        "///",
        "/// One line per entry, and `rustfmt` is told to leave them alone, following the web-assets",
        "/// generator this one is modelled on.",
        "#[rustfmt::skip]",
        "pub const BINARIES: &[Entry] = &[",
    ]
    for entry in sorted(built, key=lambda b: b.triple):
        lines.append(
            f'    Entry {{ triple: "{entry.triple}", '
            f'path: "{rust_escape(str(entry.path))}", '
            f'sha256: "{entry.sha256}", len: {entry.len} }},'
        )
    lines += [
        "];",
        "",
    ]
    return "\n".join(lines)


def run_snapshot(out: Path) -> int:
    version = drone_version()
    console.print(f"[bold]snapshot[/bold] ubiq-drone {version}\n")

    built: list[Built] = []
    skipped: list[str] = []
    for triple in TRIPLES:
        path = binary_path(triple)
        if not path.is_file():
            skipped.append(triple)
            continue
        sha256, length = hash_file(path)
        built.append(Built(triple=triple, path=path.relative_to(REPO), sha256=sha256, len=length))

    if skipped:
        console.print(f"[yellow]skipped {len(skipped)} triple(s) with no built binary:[/yellow]")
        for triple in skipped:
            console.print(f"  {triple} — {binary_path(triple).relative_to(REPO)} not found")
        console.print()

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_manifest(version, built))

    table = Table(show_header=False, box=None, pad_edge=False)
    table.add_row("built", f"{len(built)} of {len(TRIPLES)} triples")
    table.add_row("VERSION", version)
    table.add_row("written", str(out.relative_to(REPO)))
    console.print(table)
    if not built:
        console.print(
            "\n[yellow]no binaries found — this is expected without a cross toolchain; "
            "the manifest still compiles with an empty table[/yellow]"
        )
    return 0


ENTRY_RE = re.compile(
    r'Entry \{ triple: "([^"]+)", path: "([^"]+)", sha256: "([0-9a-f]{64})", len: (\d+) \}'
)


def run_verify(out: Path) -> int:
    if not out.is_file():
        die(f"no manifest at {out} — run `just drone-manifest` first")
    text = out.read_text()
    entries = ENTRY_RE.findall(text)
    console.print(f"[bold]verify[/bold] {len(entries)} binaries against {out.relative_to(REPO)}\n")
    if not entries:
        console.print("[green]nothing to verify[/green] — the table is empty")
        return 0

    drift: list[tuple[str, str]] = []
    for triple, rel_path, sha, length in entries:
        path = REPO / rel_path
        if not path.is_file():
            drift.append((triple, f"{rel_path} is gone"))
            continue
        got_sha, got_len = hash_file(path)
        if got_sha != sha:
            drift.append((triple, f"sha256 {sha[:12]}… → {got_sha[:12]}…"))
        elif got_len != int(length):
            drift.append((triple, f"len {length} → {got_len}"))

    if drift:
        console.print(f"[red]{len(drift)} of {len(entries)} binaries drifted[/red]")
        for triple, detail in drift:
            console.print(f"  {triple} — {detail}")
        console.print("\nthe local build changed; re-run `just drone-manifest`")
        return 1
    console.print(f"[green]no drift[/green] — all {len(entries)} binaries match the manifest")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["snapshot", "verify"])
    parser.add_argument("--out", type=Path, default=MANIFEST, help="generated manifest path")
    args = parser.parse_args()

    match args.action:
        case "snapshot":
            return run_snapshot(args.out)
        case "verify":
            return run_verify(args.out)
    return 2


if __name__ == "__main__":
    sys.exit(main())
