//! Ubiq's own icons, as Rust — **generated by `just icons-gen`, do not edit**.
//!
//! One variant per row of `assets/icons/icons.yaml` that has a file of ours. A row sourced
//! `lucide:` is left out on purpose: `gpui_component::IconName` already names that variant, and a
//! second spelling of the same borrowed icon is exactly the drift the registry exists to prevent.
//!
//! [`IconNamed`] is what makes this usable: the blanket `From<T> for Icon` means a variant passes
//! anywhere an `IconName` does. The paths it returns are resolved by the asset source
//! `ubiq-app` registers, which reads them out of [`bytes`].

use gpui::SharedString;
use gpui_component::IconNamed;

/// An icon Ubiq draws itself.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum UbiqIcon {
    /// photograph this window into an editable tab — the picture, not just a frame
    CaptureWindow,
    /// a notification from a connector
    FamilyConnectors,
    /// a notification from the application itself
    FamilyUbiq,
    /// a path that is new in this change
    GitAdded,
    /// a branch, told apart from a remote host
    GitBranch,
    /// a path this change removes
    GitDeleted,
    /// a path whose contents changed
    GitModified,
    /// a path that moved, its old name shown beside it
    GitRenamed,
    /// a path whose kind changed — file to link, or link to file
    GitTypeChange,
    /// a path git has never been told about
    GitUntracked,
    /// Google's Antigravity
    HarnessAntigravity,
    /// a harness with no mark of its own — every one we have not drawn yet lands here
    HarnessAny,
    /// Anthropic's Claude Code, told apart from the other marks at a glance
    HarnessClaudeCode,
    /// OpenAI's Codex CLI
    HarnessCodex,
    /// GitHub's Copilot CLI
    HarnessCopilotCli,
    /// Google's Gemini CLI
    HarnessGeminiCli,
    /// xAI's Grok CLI
    HarnessGrok,
    /// opencode — its frame, with the block at the foot standing in for the logo's shadow
    HarnessOpencode,
    /// a host on another machine, told apart from a branch and from a connector
    HostRemote,
    /// a harness running inside a sandbox, told apart from capturing the window
    Isolation,
    /// the columns of agent conversations, no harness named
    ModeAgents,
    /// the application's own dashboard
    ModeControl,
    /// the project's git state
    ModeGit,
    /// the editor and its panels — the mode, not the terminal inside it
    ModeIde,
    /// the project's knowledge base
    ModeKb,
    /// the style reference, where every primitive is looked at side by side
    ModeSink,
    /// work items that leave the board once done — a square whose corner is open and a tick on its way out through it
    ModeTasks,
    /// the orchestration graph of agents working together
    ModeTeams,
    /// the harness has stopped and is waiting for the reader to answer
    PaneAwaiting,
    /// the harness is working, with no measurable progress to report
    PaneThinking,
    /// a conversation that exists but has no process behind it
    PaneUnloaded,
    /// the node that investigates and reports, without the search field's icon
    RoleAnalyst,
    /// the node that plans and hands out work
    RoleManager,
    /// the node that checks another node's work
    RoleVerifier,
    /// a node whose role has no icon of its own — the honest fallback
    RoleWorker,
    /// a tab protected from close, drawn before its label
    TabPin,
    /// open the project in a browser
    TitlebarBrowser,
    /// the notification centre
    TitlebarNotifications,
    /// show or hide the bottom region
    TitlebarPanelBottom,
    /// show or hide the left region
    TitlebarPanelLeft,
    /// show or hide the right region
    TitlebarPanelRight,
    /// search the project
    TitlebarSearch,
    /// the settings screen
    TitlebarSettings,
    /// switch to the dark palette
    TitlebarThemeDark,
    /// switch to the light palette
    TitlebarThemeLight,
    /// the harness handed the work to a subagent
    ToolDelegate,
    /// the harness changed a file in place — a page and the pen that changed it
    ToolEdit,
    /// the harness moved or renamed a path
    ToolMove,
    /// the harness changed its own permission mode mid-turn
    ToolSwitchMode,
    /// the harness reasoned without touching anything
    ToolThink,
    /// files arranged as a flat list, told apart from the keyboard settings page
    ViewList,
    /// files arranged as a tree, told apart from toggling the left region
    ViewTree,
}

impl IconNamed for UbiqIcon {
    fn path(self) -> SharedString {
        SharedString::new_static(match self {
            Self::CaptureWindow => "icons/capture-window.svg",
            Self::FamilyConnectors => "icons/family-connectors.svg",
            Self::FamilyUbiq => "icons/family-ubiq.svg",
            Self::GitAdded => "icons/git-added.svg",
            Self::GitBranch => "icons/git-branch.svg",
            Self::GitDeleted => "icons/git-deleted.svg",
            Self::GitModified => "icons/git-modified.svg",
            Self::GitRenamed => "icons/git-renamed.svg",
            Self::GitTypeChange => "icons/git-type-change.svg",
            Self::GitUntracked => "icons/git-untracked.svg",
            Self::HarnessAntigravity => "icons/harness-antigravity.svg",
            Self::HarnessAny => "icons/harness-any.svg",
            Self::HarnessClaudeCode => "icons/harness-claude-code.svg",
            Self::HarnessCodex => "icons/harness-codex.svg",
            Self::HarnessCopilotCli => "icons/harness-copilot-cli.svg",
            Self::HarnessGeminiCli => "icons/harness-gemini-cli.svg",
            Self::HarnessGrok => "icons/harness-grok.svg",
            Self::HarnessOpencode => "icons/harness-opencode.svg",
            Self::HostRemote => "icons/host-remote.svg",
            Self::Isolation => "icons/isolation.svg",
            Self::ModeAgents => "icons/mode-agents.svg",
            Self::ModeControl => "icons/mode-control.svg",
            Self::ModeGit => "icons/mode-git.svg",
            Self::ModeIde => "icons/mode-ide.svg",
            Self::ModeKb => "icons/mode-kb.svg",
            Self::ModeSink => "icons/mode-sink.svg",
            Self::ModeTasks => "icons/mode-tasks.svg",
            Self::ModeTeams => "icons/mode-teams.svg",
            Self::PaneAwaiting => "icons/pane-awaiting.svg",
            Self::PaneThinking => "icons/pane-thinking.svg",
            Self::PaneUnloaded => "icons/pane-unloaded.svg",
            Self::RoleAnalyst => "icons/role-analyst.svg",
            Self::RoleManager => "icons/role-manager.svg",
            Self::RoleVerifier => "icons/role-verifier.svg",
            Self::RoleWorker => "icons/role-worker.svg",
            Self::TabPin => "icons/tab-pin.svg",
            Self::TitlebarBrowser => "icons/titlebar-browser.svg",
            Self::TitlebarNotifications => "icons/titlebar-notifications.svg",
            Self::TitlebarPanelBottom => "icons/titlebar-panel-bottom.svg",
            Self::TitlebarPanelLeft => "icons/titlebar-panel-left.svg",
            Self::TitlebarPanelRight => "icons/titlebar-panel-right.svg",
            Self::TitlebarSearch => "icons/titlebar-search.svg",
            Self::TitlebarSettings => "icons/titlebar-settings.svg",
            Self::TitlebarThemeDark => "icons/titlebar-theme-dark.svg",
            Self::TitlebarThemeLight => "icons/titlebar-theme-light.svg",
            Self::ToolDelegate => "icons/tool-delegate.svg",
            Self::ToolEdit => "icons/tool-edit.svg",
            Self::ToolMove => "icons/tool-move.svg",
            Self::ToolSwitchMode => "icons/tool-switch-mode.svg",
            Self::ToolThink => "icons/tool-think.svg",
            Self::ViewList => "icons/view-list.svg",
            Self::ViewTree => "icons/view-tree.svg",
        })
    }
}

/// Every variant, so a test can assert each one still has a file behind it.
pub const ALL: &[UbiqIcon] = &[
    UbiqIcon::CaptureWindow,
    UbiqIcon::FamilyConnectors,
    UbiqIcon::FamilyUbiq,
    UbiqIcon::GitAdded,
    UbiqIcon::GitBranch,
    UbiqIcon::GitDeleted,
    UbiqIcon::GitModified,
    UbiqIcon::GitRenamed,
    UbiqIcon::GitTypeChange,
    UbiqIcon::GitUntracked,
    UbiqIcon::HarnessAntigravity,
    UbiqIcon::HarnessAny,
    UbiqIcon::HarnessClaudeCode,
    UbiqIcon::HarnessCodex,
    UbiqIcon::HarnessCopilotCli,
    UbiqIcon::HarnessGeminiCli,
    UbiqIcon::HarnessGrok,
    UbiqIcon::HarnessOpencode,
    UbiqIcon::HostRemote,
    UbiqIcon::Isolation,
    UbiqIcon::ModeAgents,
    UbiqIcon::ModeControl,
    UbiqIcon::ModeGit,
    UbiqIcon::ModeIde,
    UbiqIcon::ModeKb,
    UbiqIcon::ModeSink,
    UbiqIcon::ModeTasks,
    UbiqIcon::ModeTeams,
    UbiqIcon::PaneAwaiting,
    UbiqIcon::PaneThinking,
    UbiqIcon::PaneUnloaded,
    UbiqIcon::RoleAnalyst,
    UbiqIcon::RoleManager,
    UbiqIcon::RoleVerifier,
    UbiqIcon::RoleWorker,
    UbiqIcon::TabPin,
    UbiqIcon::TitlebarBrowser,
    UbiqIcon::TitlebarNotifications,
    UbiqIcon::TitlebarPanelBottom,
    UbiqIcon::TitlebarPanelLeft,
    UbiqIcon::TitlebarPanelRight,
    UbiqIcon::TitlebarSearch,
    UbiqIcon::TitlebarSettings,
    UbiqIcon::TitlebarThemeDark,
    UbiqIcon::TitlebarThemeLight,
    UbiqIcon::ToolDelegate,
    UbiqIcon::ToolEdit,
    UbiqIcon::ToolMove,
    UbiqIcon::ToolSwitchMode,
    UbiqIcon::ToolThink,
    UbiqIcon::ViewList,
    UbiqIcon::ViewTree,
];

/// One row's file, embedded. A macro because the arm is otherwise the same long path fifty times
/// over, and rustfmt then wraps every one of them.
macro_rules! ours {
    ($name:literal) => {
        include_bytes!(concat!("../../../../../assets/icons/", $name, ".svg")).as_slice()
    };
}

/// The bytes behind one of our icon paths, or `None` for anything that is not ours.
///
/// This is what the application's asset source consults before falling through to the set
/// `gpui-component` ships.
pub fn bytes(path: &str) -> Option<&'static [u8]> {
    Some(match path {
        "icons/capture-window.svg" => ours!("capture-window"),
        "icons/family-connectors.svg" => ours!("family-connectors"),
        "icons/family-ubiq.svg" => ours!("family-ubiq"),
        "icons/git-added.svg" => ours!("git-added"),
        "icons/git-branch.svg" => ours!("git-branch"),
        "icons/git-deleted.svg" => ours!("git-deleted"),
        "icons/git-modified.svg" => ours!("git-modified"),
        "icons/git-renamed.svg" => ours!("git-renamed"),
        "icons/git-type-change.svg" => ours!("git-type-change"),
        "icons/git-untracked.svg" => ours!("git-untracked"),
        "icons/harness-antigravity.svg" => ours!("harness-antigravity"),
        "icons/harness-any.svg" => ours!("harness-any"),
        "icons/harness-claude-code.svg" => ours!("harness-claude-code"),
        "icons/harness-codex.svg" => ours!("harness-codex"),
        "icons/harness-copilot-cli.svg" => ours!("harness-copilot-cli"),
        "icons/harness-gemini-cli.svg" => ours!("harness-gemini-cli"),
        "icons/harness-grok.svg" => ours!("harness-grok"),
        "icons/harness-opencode.svg" => ours!("harness-opencode"),
        "icons/host-remote.svg" => ours!("host-remote"),
        "icons/isolation.svg" => ours!("isolation"),
        "icons/mode-agents.svg" => ours!("mode-agents"),
        "icons/mode-control.svg" => ours!("mode-control"),
        "icons/mode-git.svg" => ours!("mode-git"),
        "icons/mode-ide.svg" => ours!("mode-ide"),
        "icons/mode-kb.svg" => ours!("mode-kb"),
        "icons/mode-sink.svg" => ours!("mode-sink"),
        "icons/mode-tasks.svg" => ours!("mode-tasks"),
        "icons/mode-teams.svg" => ours!("mode-teams"),
        "icons/pane-awaiting.svg" => ours!("pane-awaiting"),
        "icons/pane-thinking.svg" => ours!("pane-thinking"),
        "icons/pane-unloaded.svg" => ours!("pane-unloaded"),
        "icons/role-analyst.svg" => ours!("role-analyst"),
        "icons/role-manager.svg" => ours!("role-manager"),
        "icons/role-verifier.svg" => ours!("role-verifier"),
        "icons/role-worker.svg" => ours!("role-worker"),
        "icons/tab-pin.svg" => ours!("tab-pin"),
        "icons/titlebar-browser.svg" => ours!("titlebar-browser"),
        "icons/titlebar-notifications.svg" => ours!("titlebar-notifications"),
        "icons/titlebar-panel-bottom.svg" => ours!("titlebar-panel-bottom"),
        "icons/titlebar-panel-left.svg" => ours!("titlebar-panel-left"),
        "icons/titlebar-panel-right.svg" => ours!("titlebar-panel-right"),
        "icons/titlebar-search.svg" => ours!("titlebar-search"),
        "icons/titlebar-settings.svg" => ours!("titlebar-settings"),
        "icons/titlebar-theme-dark.svg" => ours!("titlebar-theme-dark"),
        "icons/titlebar-theme-light.svg" => ours!("titlebar-theme-light"),
        "icons/tool-delegate.svg" => ours!("tool-delegate"),
        "icons/tool-edit.svg" => ours!("tool-edit"),
        "icons/tool-move.svg" => ours!("tool-move"),
        "icons/tool-switch-mode.svg" => ours!("tool-switch-mode"),
        "icons/tool-think.svg" => ours!("tool-think"),
        "icons/view-list.svg" => ours!("view-list"),
        "icons/view-tree.svg" => ours!("view-tree"),
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_variant_resolves() {
        for icon in ALL {
            let path = icon.path();
            assert!(bytes(&path).is_some_and(|b| !b.is_empty()), "{path}");
        }
    }
}
