//! The schema stage (V3) against Archify itself.
//!
//! - every Archify example (the `source_doc` of the `example` goldens) has zero schema diagnostics;
//! - `schema_cases.json` (generated by `gen-schema-cases.mjs` from Archify's own
//!   `validateSchema`) holds hand-mutated documents and the exact diagnostics Archify emits for
//!   them: code, message, subject, evidence and fixes must all agree, in order;
//! - the P0.5 goldens in `tests/fixtures/` agree on `(code, path)` (after the receipt's dedup).

use std::fs;
use std::path::{Path, PathBuf};

use ubiq_archify::diag::dedup_by_message;
use ubiq_archify::schema::{self, DOC_TYPES};
use serde_json::{Value, json};

fn crate_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// The Archify examples: the `source_doc` of the `example` goldens, by file name.
fn examples() -> Vec<(String, Value)> {
    let dir = crate_dir().join("tests/fixtures");
    let mut out = Vec::new();
    for entry in fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();
        if !path.to_string_lossy().ends_with(".golden.json") {
            continue;
        }
        let golden = read_json(&path);
        if golden["group"] != "example" {
            continue;
        }
        let name = golden["source"].as_str().unwrap().rsplit('/').next().unwrap().to_owned();
        out.push((name, golden["source_doc"].clone()));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn read_json(path: &Path) -> Value {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

/// `name.<type>.json` to `<type>`.
fn type_of(file_name: &str) -> Option<&'static str> {
    let stem = file_name.strip_suffix(".json")?;
    let kind = stem.rsplit('.').next()?;
    DOC_TYPES.iter().copied().find(|t| *t == kind)
}

/// JSON mode collapses same-message diagnostics: a 3-item `point` reports `maxItems` and `items`
/// with one message, and Archify's receipt keeps the first.
#[test]
fn a_third_point_coordinate_is_one_receipt_diagnostic() {
    let mut doc = json!({"schema_version": 1, "diagram_type": "architecture",
        "meta": {"title": "t", "output": "a.html"},
        "components": [{"id": "a", "type": "backend", "label": "A", "pos": [1, 2, 3]}]});
    let all = schema::validate("architecture", &doc);
    let codes: Vec<_> = all.iter().map(|d| d.code.as_str()).collect();
    assert_eq!(codes, ["schema/maxItems", "schema/items"]);
    assert_eq!(dedup_by_message(all).len(), 1);
    doc["components"][0]["pos"] = json!([1, 2]);
    assert!(schema::validate("architecture", &doc).is_empty());
}

fn render(diagnostics: &[ubiq_archify::diag::Diagnostic]) -> String {
    diagnostics
        .iter()
        .map(|d| {
            format!(
                "  {} {} {}",
                d.code,
                d.subject.path.as_deref().unwrap_or("-"),
                d.message
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn every_archify_example_passes_the_schema_stage() {
    let mut checked = 0;
    for (name, doc) in examples() {
        let Some(doc_type) = type_of(&name) else {
            continue;
        };
        let diagnostics = schema::validate(doc_type, &doc);
        assert!(diagnostics.is_empty(), "{name}:\n{}", render(&diagnostics));
        checked += 1;
    }
    assert!(checked >= 10, "only {checked} examples found");
}

fn apply_ops(doc: &mut Value, ops: &[Value]) {
    for op in ops {
        let (kind, ptr) = (op[0].as_str().unwrap(), op[1].as_str().unwrap());
        let (parent_ptr, key) = ptr.rsplit_once('/').unwrap();
        let key = key.replace("~1", "/").replace("~0", "~");
        let parent = doc
            .pointer_mut(parent_ptr)
            .unwrap_or_else(|| panic!("{ptr}"));
        let set = |parent: &mut Value, value: Value| match parent {
            Value::Array(items) => items[key.parse::<usize>().unwrap()] = value,
            Value::Object(map) => {
                map.insert(key.clone(), value);
            }
            other => panic!("{ptr} under {other}"),
        };
        match kind {
            "set" => set(parent, op[2].clone()),
            "del" => {
                parent.as_object_mut().unwrap().remove(&key);
            }
            "fill" => {
                let n = op[2].as_u64().unwrap();
                let object: serde_json::Map<String, Value> =
                    (0..n).map(|i| (format!("k{i}"), json!("x"))).collect();
                set(parent, Value::Object(object));
            }
            other => panic!("unknown op {other}"),
        }
    }
}

#[test]
fn hand_mutated_documents_get_archifys_diagnostics() {
    let examples = examples();
    let cases = read_json(&crate_dir().join("tests/schema_cases.json"));
    let cases = cases["cases"].as_array().unwrap();
    assert!(cases.len() >= 100, "{} cases", cases.len());

    let mut failures = Vec::new();
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let doc_type = case["type"].as_str().unwrap();
        let doc = match case["base"].as_str() {
            Some(base) => {
                let mut doc = examples.iter().find(|(n, _)| n == base).unwrap_or_else(|| panic!("{base}: no such example")).1.clone();
                apply_ops(&mut doc, case["ops"].as_array().unwrap());
                doc
            }
            None => case["doc"].clone(),
        };
        // `subject.rule` is ours (D7); everything else is Archify's.
        let ours: Vec<Value> = schema::validate(doc_type, &doc)
            .iter()
            .map(|d| {
                let mut v = serde_json::to_value(d).unwrap();
                v["subject"].as_object_mut().unwrap().remove("rule");
                v
            })
            .collect();
        let theirs = case["diagnostics"].as_array().unwrap();
        if ours.len() != theirs.len() {
            failures.push(format!(
                "{name}: {} diagnostics, Archify {}\n{:#?}\nvs\n{:#?}",
                ours.len(),
                theirs.len(),
                ours,
                theirs
            ));
            continue;
        }
        for (i, (a, b)) in ours.iter().zip(theirs).enumerate() {
            if a != b {
                failures.push(format!("{name}[{i}]:\n  ours   {a}\n  theirs {b}"));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn goldens_agree_on_schema_code_and_path() {
    let dir = crate_dir().join("tests/fixtures");
    let mut checked = 0;
    let mut failures = Vec::new();
    for entry in fs::read_dir(&dir).unwrap_or_else(|e| panic!("{}: {e}", dir.display())) {
        let path = entry.unwrap().path();
        if !path.to_string_lossy().ends_with(".golden.json") {
            continue;
        }
        let golden = read_json(&path);
        let (Some(doc), Some(doc_type)) = (golden.get("source_doc"), golden["type"].as_str())
        else {
            continue;
        };
        let Some(diagnostics) = golden
            .pointer("/validate_receipt/authored/receipt/diagnostics")
            .and_then(Value::as_array)
        else {
            // A passing receipt carries none: the stage must produce none.
            if golden.pointer("/validate_receipt/authored/receipt/ok") == Some(&json!(true)) {
                let ours = schema::validate(doc_type, doc);
                if !ours.is_empty() {
                    failures.push(format!(
                        "{}: expected none\n{}",
                        path.display(),
                        render(&ours)
                    ));
                }
                checked += 1;
            }
            continue;
        };
        let code_of = |d: &Value| d["code"].as_str().unwrap_or_default().to_owned();
        // V1/V2 stop before the schema stage: nothing to compare.
        if diagnostics.iter().any(|d| {
            let code = code_of(d);
            code.starts_with("input/") || code.starts_with("output/")
        }) {
            continue;
        }
        let key = |code: &str, p: &str| format!("{code} {p}");
        let mut theirs: Vec<String> = diagnostics
            .iter()
            .filter(|d| code_of(d).starts_with("schema/"))
            .map(|d| key(&code_of(d), d["subject"]["path"].as_str().unwrap_or("/")))
            .collect();
        // Receipts are JSON mode: duplicate messages collapse (`items` repeats `maxItems`).
        let mut ours: Vec<String> = dedup_by_message(schema::validate(doc_type, doc))
            .iter()
            .map(|d| key(&d.code, d.subject.path.as_deref().unwrap_or("/")))
            .collect();
        theirs.sort();
        ours.sort();
        if ours != theirs {
            failures.push(format!(
                "{}:\n  ours   {ours:?}\n  theirs {theirs:?}",
                path.display()
            ));
        }
        checked += 1;
    }
    assert!(
        checked >= 50,
        "only {checked} usable goldens in {}",
        dir.display()
    );
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
