//! The cross-built `ubiq-drone` binaries a deployer can hand to a remote machine, with the
//! SHA-256 [`crate::drone::verify`] checks a cached copy against.
//!
//! **This is hash-pinned, not signed.** There is no signing key and no release pipeline
//! (`G108`); a mismatch here means the local build changed, not that a signature failed —
//! saying "signed" would imply provenance this tree does not have.
//!
//! A triple with no locally built binary at snapshot time is simply absent from
//! [`BINARIES`]: nobody has every cross toolchain installed, so a partial manifest is the
//! honest state, not a failed run.
//!
//! @generated by `_tools/drone.py` — do not edit by hand.
//! Regenerate with `just drone-manifest`; check for local drift with
//! `just drone-manifest-verify`.

/// One cross-built binary: which triple it runs on, where `snapshot` found it, and what it
/// must hash to.
pub struct Entry {
    pub triple: &'static str,
    pub path: &'static str,
    pub sha256: &'static str,
    pub len: u64,
}

/// `ubiq-drone`'s own `CARGO_PKG_VERSION` — the cache directory name a deployer keys its
/// copy under, so two versions never collide on disk.
pub const VERSION: &str = "0.1.0";

/// The 0 triple(s) built locally when this manifest was last regenerated, sorted
/// by triple.
///
/// One line per entry, and `rustfmt` is told to leave them alone, following the web-assets
/// generator this one is modelled on.
#[rustfmt::skip]
pub const BINARIES: &[Entry] = &[
];
