#!/usr/bin/env python
# Merge the four wireframe screens into one board, offsetting each into a 2x2 grid.
import yaml, copy

COL0, COL1 = 0, 1480
ROW1, ROW2 = 170, 1210

SCREENS = [
    ("01-projects.excalidraw.yaml",  "1  ·  Projects / Launcher",        COL0, ROW1),
    ("02-session.excalidraw.yaml",   "2  ·  Session (single agent)",     COL1, ROW1),
    ("04-settings.excalidraw.yaml",  "4  ·  Settings",                   COL0, ROW2),
    ("03-subagents.excalidraw.yaml", "3  ·  Subagents fan-out",          COL1, ROW2),
]

def shift(d, dx, dy):
    if isinstance(d.get("at"), list):    d["at"]    = [d["at"][0]+dx,    d["at"][1]+dy]
    if isinstance(d.get("start"), list): d["start"] = [d["start"][0]+dx, d["start"][1]+dy]
    if isinstance(d.get("end"), list):   d["end"]   = [d["end"][0]+dx,   d["end"][1]+dy]
    if "x" in d and isinstance(d["x"], (int, float)): d["x"] += dx
    if "y" in d and isinstance(d["y"], (int, float)): d["y"] += dy

merged = []

# board title
merged.append({"text": "Ubiq — Desktop UI Wireframes", "id": "board_title",
               "at": [0, 24], "fontSize": 36, "align": "left", "stroke": "#212529"})
merged.append({"text": "harness multiplexer · project launcher → session → subagents · settings",
               "id": "board_sub", "at": [0, 74], "fontSize": 16, "align": "left", "stroke": "#868e96"})

for i, (fname, label, dx, dy) in enumerate(SCREENS, 1):
    doc = yaml.safe_load(open(fname))
    # screen label above its frame
    merged.append({"text": label, "id": f"label_{i}", "at": [dx+20, dy-46],
                   "fontSize": 24, "align": "left", "stroke": "#4263eb"})
    for el in doc["elements"]:
        el = copy.deepcopy(el)
        shift(el, dx, dy)
        for k, v in el.items():
            if isinstance(v, dict):
                shift(v, dx, dy)
                if "id" in v:
                    v["id"] = f"s{i}_{v['id']}"
        if "id" in el:
            el["id"] = f"s{i}_{el['id']}"
        merged.append(el)

# ---- flow arrows between screens (drawn on top, explicit endpoints) ----
def arrow(a, b, eid):
    return {"arrow": {"id": eid, "start": list(a), "end": list(b),
                      "stroke": "#e64980", "strokeWidth": "bold"}}
def flowlabel(txt, at, eid):
    return {"text": txt, "id": eid, "at": list(at), "fontSize": 18,
            "align": "left", "stroke": "#e64980"}

# S1 -> S2 : create / open a session   (right edge of S1 to left edge of S2)
y12 = ROW1 + 440
merged.append(arrow((COL0 + 1344, y12), (COL1 + 16, y12), "flow_12"))
merged.append(flowlabel("create / open", (COL0 + 1352, y12 - 44), "flow_12_l"))
# S2 -> S3 : add agent -> subagents     (bottom of S2 down to top of S3)
x23 = COL1 + 680
merged.append(arrow((x23, ROW1 + 864), (x23, ROW2 + 14), "flow_23"))
merged.append(flowlabel("＋ add agent", (x23 + 16, (ROW1 + 864 + ROW2) // 2), "flow_23_l"))
# S1 -> S4 : open settings              (bottom of S1 down to top of S4)
x14 = COL0 + 680
merged.append(arrow((x14, ROW1 + 864), (x14, ROW2 + 14), "flow_14"))
merged.append(flowlabel("⚙ settings", (x14 + 16, (ROW1 + 864 + ROW2) // 2), "flow_14_l"))

out = {
    "version": 1,
    "canvas": {"background": "#eef0f2", "theme": "light"},
    "layout": {"mode": "none"},
    "defaults": {"roughness": 0, "strokeWidth": "thin", "fontFamily": "normal"},
    "elements": merged,
}
with open("all-in-one.excalidraw.yaml", "w") as f:
    f.write("# Ubiq — all four wireframes on a single board (generated by _merge.py).\n")
    yaml.safe_dump(out, f, sort_keys=False, allow_unicode=True, default_flow_style=False, width=200)
print(f"wrote all-in-one.excalidraw.yaml with {len(merged)} elements")
