//! The `ubiq` command: a small generated script on the shell's `PATH` that hands a path to the
//! application.
//!
//! It is a script and not a symbolic link, and that is the whole design. On macOS the script runs
//! `open -a Ubiq.app`, which is what makes `ubiq .` reach the *running* window through
//! LaunchServices instead of starting a second application beside it — a link to the executable
//! would start a second one every time. Everywhere else, and for a build with no bundle around it,
//! the script starts the binary detached from the terminal; `ubiq-app`'s handoff socket is what
//! keeps that from becoming a second application, by handing the paths to the running one.
//!
//! Every path in here belongs to the host. The interface asks for one of three actions and is told
//! what was found, which is why nothing this module exposes takes a path.

use std::fs;
use std::path::{Path, PathBuf};

use ubiq_proto::messages::{CliDir, CliShortcutAction, Message};

use crate::atomic::write_atomic;

/// The line every generated shortcut carries, followed by the path it launches.
///
/// It answers both questions this module has: *did Ubiq write this file* — so a `ubiq` of the
/// user's own is never deleted — and *which build does it launch*, which is what makes a shortcut
/// left behind by a moved or replaced application detectable rather than mysterious.
const MARKER: &str = "ubiq-target:";

#[cfg(windows)]
const NAME: &str = "ubiq.cmd";
#[cfg(not(windows))]
const NAME: &str = "ubiq";

/// Look, write or delete, and answer what is there afterwards either way.
pub fn handle(action: CliShortcutAction) -> Message {
    let error = match action {
        CliShortcutAction::Query => None,
        CliShortcutAction::Install => install().err(),
        CliShortcutAction::Remove => remove().err(),
    };
    state(error)
}

/// What the shortcut launches: the surrounding `.app` on macOS, the executable itself otherwise.
fn target() -> Result<PathBuf, String> {
    let exe = std::env::current_exe().map_err(|error| format!("no executable path: {error}"))?;
    if cfg!(target_os = "macos") {
        // `…/Ubiq.app/Contents/MacOS/ubiq` → `…/Ubiq.app`. Running from `cargo run` there is no
        // bundle, and the plain executable is both the honest answer and the useful one.
        if let Some(bundle) = exe
            .ancestors()
            .find(|path| path.extension().is_some_and(|ext| ext == "app"))
        {
            return Ok(bundle.to_path_buf());
        }
    }
    Ok(exe)
}

/// The script that launches `target`.
fn script(path: &Path) -> String {
    let bundle = path.extension().is_some_and(|ext| ext == "app");
    let target = path.display();
    if cfg!(windows) {
        format!(
            "@echo off\r\n\
             :: Generated by Ubiq. Remove it from Settings \u{203a} Command line.\r\n\
             :: {MARKER} {target}\r\n\
             start \"\" \"{target}\" %*\r\n"
        )
    } else if cfg!(target_os = "macos") && bundle {
        format!(
            "#!/bin/sh\n\
             # Generated by Ubiq. Remove it from Settings \u{203a} Command line.\n\
             # {MARKER} {target}\n\
             exec open -a \"{target}\" \"$@\"\n"
        )
    } else {
        // No LaunchServices to go through, so the script starts a process itself — detached, and
        // with the terminal's streams let go, because a command line is not where a window should
        // report to. Which process ends up drawing is `ubiq-app`'s handoff socket's answer: a
        // second launch under the same config root hands its paths to the running application and
        // exits, so this starts one only when there is none.
        format!(
            "#!/bin/sh\n\
             # Generated by Ubiq. Remove it from Settings \u{203a} Command line.\n\
             # {MARKER} {target}\n\
             \"{target}\" \"$@\" >/dev/null 2>&1 &\n"
        )
    }
}

fn home() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|dirs| dirs.home_dir().to_path_buf())
}

fn path_dirs() -> Vec<PathBuf> {
    std::env::var_os("PATH")
        .map(|path| std::env::split_paths(&path).collect())
        .unwrap_or_default()
}

/// Every directory the shortcut could live in, best first.
///
/// The conventional user-owned ones lead, because a command the user installed belongs in their
/// own tree; whatever else is already on their `PATH` under their home directory follows, so a
/// machine set up some other way still has somewhere to put it.
fn candidates() -> Vec<PathBuf> {
    let home = home();
    let mut dirs: Vec<PathBuf> = Vec::new();

    if let Some(home) = &home {
        if cfg!(windows) {
            dirs.push(home.join("AppData/Local/Microsoft/WindowsApps"));
        } else {
            dirs.push(home.join(".local/bin"));
        }
    }
    if !cfg!(windows) {
        dirs.push(PathBuf::from("/usr/local/bin"));
        if let Some(home) = &home {
            dirs.push(home.join("bin"));
        }
    }
    if let Some(home) = &home {
        dirs.extend(path_dirs().into_iter().filter(|dir| dir.starts_with(home)));
    }

    let mut unique: Vec<PathBuf> = Vec::new();
    for dir in dirs {
        if !unique.contains(&dir) {
            unique.push(dir);
        }
    }
    unique
}

/// The path on the `MARKER` line of a file, if the file has one.
fn marked_target(file: &Path) -> Option<String> {
    let text = fs::read_to_string(file).ok()?;
    text.lines()
        .find_map(|line| line.split_once(MARKER))
        .map(|(_, rest)| rest.trim().to_string())
}

/// The first candidate holding a shortcut this application wrote.
fn installed() -> Option<(PathBuf, String)> {
    candidates()
        .into_iter()
        .map(|dir| dir.join(NAME))
        .find_map(|file| marked_target(&file).map(|target| (file, target)))
}

/// Where a shortcut would be written: beside one that is already there, else the first directory
/// *in the user's own tree* the shell would find, else `~/.local/bin`, which install creates.
///
/// **Only ever the user's own tree.** `/usr/local/bin` is on the list because a shortcut already
/// sitting there has to be found and removable, but it is root-owned on a stock machine, and
/// choosing it would answer a button press with a permission error while a directory the user can
/// write to was one line above it.
fn install_dir() -> Option<PathBuf> {
    if let Some((file, _)) = installed() {
        return file.parent().map(Path::to_path_buf);
    }
    let home = home()?;
    let on_path = path_dirs();
    let dirs = candidates();
    dirs.iter()
        .find(|dir| dir.starts_with(&home) && dir.is_dir() && on_path.contains(dir))
        .or_else(|| dirs.iter().find(|dir| dir.starts_with(&home)))
        .map(PathBuf::from)
}

fn install() -> Result<(), String> {
    let target = target()?;
    let dir = install_dir().ok_or_else(|| "no directory to install into".to_string())?;
    install_into(&dir, &target)
}

/// The half that takes its paths rather than finding them, so it can be exercised against a
/// temporary directory without touching the machine's own `PATH`.
fn install_into(dir: &Path, target: &Path) -> Result<(), String> {
    let file = dir.join(NAME);
    write_atomic(&file, script(target).as_bytes())
        .map_err(|error| format!("could not write {}: {error}", file.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        fs::set_permissions(&file, fs::Permissions::from_mode(0o755))
            .map_err(|error| format!("could not make {} executable: {error}", file.display()))?;
    }
    Ok(())
}

fn remove() -> Result<(), String> {
    let Some((file, _)) = installed() else {
        return Ok(());
    };
    remove_at(&file)
}

/// Delete one, and only a file carrying the marker: a `ubiq` the user put on their own `PATH` is
/// theirs, and this never touches it.
fn remove_at(file: &Path) -> Result<(), String> {
    if marked_target(file).is_none() {
        return Ok(());
    }
    fs::remove_file(file).map_err(|error| format!("could not remove {}: {error}", file.display()))
}

fn state(error: Option<String>) -> Message {
    let target = target().ok();
    let installed = installed();
    let on_path = path_dirs();
    let chosen = install_dir();

    Message::CliShortcutState {
        stale: match (&installed, &target) {
            (Some((_, marked)), Some(target)) => Path::new(marked) != target.as_path(),
            _ => false,
        },
        installed: installed.map(|(file, _)| file.display().to_string()),
        target: install_dir().map(|dir| dir.join(NAME).display().to_string()),
        candidates: candidates()
            .into_iter()
            .map(|dir| CliDir {
                exists: dir.is_dir(),
                on_path: on_path.contains(&dir),
                chosen: chosen.as_ref() == Some(&dir),
                path: dir.display().to_string(),
            })
            .collect(),
        error,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn installs_a_marked_executable_script() {
        let dir = tempfile::tempdir().unwrap();
        install_into(dir.path(), Path::new("/Applications/Ubiq.app")).unwrap();

        let file = dir.path().join(NAME);
        assert_eq!(
            marked_target(&file).as_deref(),
            Some("/Applications/Ubiq.app")
        );

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt as _;
            let mode = fs::metadata(&file).unwrap().permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "the shortcut has to be executable");
        }
    }

    /// The reason the shortcut is a script and not a link: `open -a` is what reaches the window
    /// that is already up. A bundle-less target has no such door and says so by exec'ing.
    #[test]
    #[cfg(target_os = "macos")]
    fn a_bundle_is_launched_through_open() {
        assert!(script(Path::new("/Applications/Ubiq.app")).contains("exec open -a"));
        let bare = script(Path::new("/tmp/target/debug/ubiq"));
        assert!(bare.contains("\"/tmp/target/debug/ubiq\" \"$@\""));
        // Detached: the shell it was typed in is not where a window reports.
        assert!(bare.trim_end().ends_with('&'));
    }

    #[test]
    fn remove_takes_ours_and_leaves_theirs() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join(NAME);

        install_into(dir.path(), Path::new("/Applications/Ubiq.app")).unwrap();
        remove_at(&file).unwrap();
        assert!(!file.exists());

        fs::write(&file, "#!/bin/sh\nexec something-else\n").unwrap();
        remove_at(&file).unwrap();
        assert!(
            file.exists(),
            "a `ubiq` we did not write is not ours to delete"
        );
    }
}
